### ISSUE TITLE
Prospector failing on my repo Py_pov

### ISSUE THREAD

**Issue by pennyarcade** [landscapeio/landscape-issues#212]
First of all best wishes for you! I am glad you are back. Get well soon!
It is very nice to see landscape.io up & running again.

Now for the crunchy stuff :-)

```
Oh No

Check number 57 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly
```

To give you a hint: Prospector runs fine locally on this project using the following  .prospector.yaml:

```
output-format: grouped

strictness: high
test-warnings: true
doc-warnings: true
# inherits:
#   - my/other/profile.yml

ignore-paths:
  - lib
  - .git

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  run: true
  # disable:
  #   - W602
  #   - W603
  enable:
    - W601
  options:
    max-line-length: 79
    single-line-if-stmt: n

pep257:
  disable:
    - D203
  run: true

pylint:
  run: true

pyroma:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 10

dodgy:
  run: true

pyflakes:
  run: true

frosted:
  run: true

vulture:
  run: true

```
