### ISSUE TITLE
uncertain failures (due to pylint?)

### ISSUE THREAD

**Issue by tomkinsc** [landscapeio/landscape-issues#220]
I'm experiencing unclear failures on a particular [repo](https://github.com/broadinstitute/viral-ngs), and am having trouble tracing the cause:
https://landscape.io/github/broadinstitute/viral-ngs

I've installed `prospector` on my local machine via `pip`, and it seems to pass without any failures when I run `prospector --die-on-tool-error ./`(under Python 2.7 or 3.5)

Here is my `.landscape.yml`:

``` yaml
requirements:
    - requirements.txt
    - requirements-pipes.txt

ignore-paths:
    - docs
    - tools/build

python-targets:
    - 2
    - 3

dodgy:
  run: yes
mccabe:
  run: yes 
pyflakes:
  run: yes
pep8:
  run: yes
pylint:
  run: yes
pep257:
  run: false # problematic for __all__ statements?
profile-validator:
  run: yes
# optional:
frosted:
  run: false
vulture:
  run: false
pyroma:
  run: false
```

Here is my `.pylintrc`:

``` yaml
[DESIGN]
# the default of five is a bit too restrictive
max-args=12

# some sci computations require many local variables
max-locals=20

[MESSAGES CONTROL]
# Enable the message, report, category or checker with the given id(s). You can
# either give multiple identifier separated by comma (,) or put this option
# multiple time.
# enable=

# Disable the message, report, category or checker with the given id(s). You
# can either give multiple identifier separated by comma (,) or put this option
# multiple time (only on the command line, not in the configuration file where
# it should appear only once).

# module has too many lines
disable=C0302

[FORMAT]
# Maximum number of characters on a single line.
max-line-length=120

[TYPECHECK]
# to prevent (incorrect) no-member errors from cython modules
ignored-modules=cython,pysam
ignored-classes=cython,pysam
```

When pylint is disabled, it does pass, but when I run pylint manually things seem OK. When pylint is enabled, prospector passes on my local machine without any apparent failures or stack traces (using `--die-on-tool-failure`). Are there other steps I can take to debug issues with landscape failures? Thanks!
