### ISSUE TITLE
How to suppress "too many ancestors" warning

### ISSUE THREAD

**Issue by holtgrewe** [landscapeio/landscape-issues#254]
I tried deactivating this in the `.landscape.yml` in different ways. What's the correct one?

Here's the problem with repository.

https://landscape.io/github/bihealth/flowcelltool/23/messages/style

Thanks,

**Comment by wolfy1339** [comment]
If you hover over the line containing the issue, it will give you the ID use that id in `.landscape.yml` to disable it
```yaml
pylint:
  disable:
    - too-many-ancestors
```
