### ISSUE TITLE
Prospector fails on my repo

### ISSUE THREAD

**Issue by mxlei01** [landscapeio/landscape-issues#288]
Hi All,

I have a repo that fails without any error messages.

This is my settings file:

```
doc-warnings: yes
test-warnings: yes
strictness: veryhigh
autodetect: yes
max-line-length: 120
requirements:
    - requirements.txt
python-targets:
    - 3
pep8:
    full: true
pylint:
    run: true
    disable:
      - too-many-return-statements
      - too-many-instance-attributes
      - too-few-public-methods
      - invalid-name
      - too-many-ancestors
      - unnecessary-lambda
pep257:
    disable:
      - D213
      - D211
      - D406
      - D407
```

When I run prospector locally, I get:

```
Check Information
=================
         Started: 2017-09-02 00:13:07.554005
        Finished: 2017-09-02 00:13:10.364902
      Time Taken: 2.81 seconds
       Formatter: grouped
        Profiles: .landscape.yml, full_pep8, doc_warnings, strictness_veryhigh, no_member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, mccabe, pep257, pep8, profile-validator, pyflakes, pylint
  Messages Found: 0
```

I have 0 errors since I fixed everything before checking in the repository.

**Comment by pennyarcade** [comment]
Hello @mxlei01 ,

some settings that are valid for prospector do not seem to work on landscape.io, especially if you installed prospector with [with-everything] locally.
The only way to debug that seems to be commenting everything in `.landscape.yml` and then commenting settings in one by one until you find the setting that breaks it.
Its a time consuming process to comment in setting, commit and push to run landscape.io again. 
@carlio: It would be very nice if the config linter would detect this :-)
I'll keep you posted what the offending setting is for me.

**Comment by pennyarcade** [comment]
Here are my results:
```
autodetect: yes
strictness: veryhigh
test-warnings: false
doc-warnings: true

ignore-paths:
  - .git
  - coverage
  - docs
  - lib
  - metrics
  - old
  - py_pov_env

ignore-patterns:
   - (^|/)skip(this)?(/|$)

pep8:
  run: true
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 79
    single-line-if-stmt: n

pylint:
  run: true

pep257:
  disable:
    - D203
  run: true

pyroma:
  run: true

mccabe:
  run: true
  options:
    max-complexity: 10

dodgy:
  run: false

pyflakes:
  run: true

frosted:
  run: true
```
works for me...

Including vulture breaks it though:
```
vulture:
  run: true
```

It took only 2 hours to find out... -.-
